### ISSUE TITLE
Impossible to install paperd, paperd fails to compile

### ISSUE THREAD

**Issue by dudeamax99** [PaperMC/paperd#4] opened 2019-12-26 00:10 UTC
`https://papermc.io/ci/view/all/job/paperd/lastSuccessfulBuild/artifact/paperd.tar.xz`
(which is used in `curl https://papermc.io/ci/view/all/job/paperd/lastSuccessfulBuild/artifact/paperd.tar.xz -o paperd.tar.xz`) returns a 404

There are no builds on the Jenkins page

Attempting to compile from source returns the following error 
```error[E0308]: mismatched types
   --> src/lib.rs:145:9
    |
145 |         m_type,
    |         ^^^^^^ expected i32, found i64
    |
help: you can convert an `i64` to `i32` and panic if the converted value wouldn't fit
    |
145 |         m_type: m_type.try_into().unwrap(),
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error

For more information about this error, try `rustc --explain E0308`.
error: could not compile `paperd-jni`.```

Thus, it is impossible to install paperd.

**Comment by DemonWav** [comment] 2019-12-30 20:27
Yeah `paperd` isn't yet available so there aren't any builds available. Once it's merged I'll do the first release.

**Comment by DemonWav** [comment] 2019-12-30 20:31
This error is caused by building with a 32 bit JDK. Only 64 bit JDKs are supported by `paperd`, I'll add a note about that in the readme.

**Closed by DemonWav** 2019-12-30 20:31 UTC
